on: [push]

jobs:
  test_action:
    runs-on: ubuntu-latest
    name: Test action
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - name: Spit out Github ref
        run: echo $GITHUB_REF

      - name: Spit out branches
        run: git branch --list

      - name: Spit out refs
        run: git for-each-ref

      - name: Spit out magic refs
        run: git for-each-ref --format='%(refname:short)' | grep -v $GITHUB_REF | sed 's/origin\///'

      - name: Test version
        id: spell
        uses: actoaps/version-spell@master

      - name: Get action output
        run: echo ${{ steps.spell.outputs.version }}
