on: [push]

jobs:
  test_action:
    runs-on: ubuntu-latest
    name: Test action
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Spit out Github ref
        run: echo $GITHUB_REF

      - name: Spit out branches
        run: git ls-remote --heads origin | grep $(git rev-parse HEAD) | sed 's?.*refs/heads/??'

      - name: Test version
        id: spell
        uses: actoaps/version-spell@master

      - name: Get action output
        run: echo ${{ steps.spell.outputs.version }}
