on: [push]

jobs:
  test_action:
    runs-on: ubuntu-latest
    name: Test action
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Test version
        id: spell
        uses: actoaps/version-spell@master

      - name: Get action output
        run: echo "${{ steps.spell.version }}"
