on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Test action
    steps:
      - name: Test version
        id: version
        uses: actoaps/version-spell@v1
#      # Use the output from the `hello` step
#      - name: Get the output time
#        run: echo "The time was ${{ steps.hello.outputs.time }}"
