on: [push]

jobs:
  test_action:
    runs-on: ubuntu-latest
    name: Test action
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Spit out Github ref
        run: echo $GITHUB_REF

      - name: Run spell without env var
        run: |
          echo refs/heads/master \
          | sed 's/refs\/heads\///' \
          | sed 's/master/dev/' \
          | sed 's/feature\///' \
          | sed 's/release\///' \
          | sed 's/$/.'"$(git rev-list --no-merges --count refs/heads/master).$(git rev-parse --short refs/heads/master)"'/'

      - name: Run spell the old fashioned way
        run: |
          export BUILD_ID=$(echo $GITHUB_REF \
          | sed 's/refs\/heads\///' \
          | sed 's/master/dev/' \
          | sed 's/feature\///' \
          | sed 's/release\///' \
          | sed 's/$/.'"$(git rev-list --no-merges --count $GITHUB_REF).$(git rev-parse --short $GITHUB_REF)"'/')

          echo $BUILD_ID

      - name: Test version
        id: spell
        uses: actoaps/version-spell@master

      - name: Get action output
        run: echo "Test 1234 ${{ steps.spell.version }}"
