on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Test action
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        
      - name: Test version
        id: version
        uses: actoaps/version-spell@master
#      # Use the output from the `hello` step
#      - name: Get the output time
#        run: echo "The time was ${{ steps.hello.outputs.time }}"
